### ISSUE TITLE
Handle any number as rating

### ISSUE THREAD

**Issue by pitchopp** [rjiandy/react-native-stars-rating#1]
I just ran into this useful plugin and tried it out. It seems to not handle rounding numbers when half stars are enabled. It would be very nice if we could set the rate prop at 3.34 and it rounds it to 3.5 stars. The formula is simple : Math.round(rate*2)/2

**Comment by rjiandy** [comment]
Hi @aminesghir thanks for using this plugin!
I just push another update according to this and add rounding feature.
Please pull version `0.1.7` and checkout the readme.

Thank you.
